# Creating physics namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: bio

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: bio
  name: bio-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: bio
  name: bio-rolebinding
subjects:
- kind: ServiceAccount
  name: bio-user
  namespace: bio
roleRef:
  kind: Role
  name: bio-role
  apiGroup: rbac.authorization.k8s.io