# Creating physics namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: physics
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: physics
  name: physics-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: physics
  name: physics-rolebinding
subjects:
- kind: ServiceAccount
  name: physics-user
  namespace: physics
roleRef:
  kind: Role
  name: physics-role
  apiGroup: rbac.authorization.k8s.io
