---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: tensorflow-
  namespace: default
  labels:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  parallelism: 1
  completions: 1
  suspend: true
  template:
    spec:
      containers:
      - name: dummy-job
        image: shubhamdang/custom_tensorflow:1.15.5
        command: [ "/bin/sh", "-c", "python " ]
        env:
          - name: MINIO_IP
            value: "10.151.15.78"
          - name: MINIO_PORT
            value: "31252"
          - name: MINIO_AKEY
            value: "Mq6wmeNk0NOc0vD9Efut"
          - name: MINIO_SKEY
            value: "Z3ETBqC3GuIiU9PomjBbmmC5h8I5I7WgN1wNWlCG"
          - name: BUCKET_NAME
            value: "tensorflow"
        resources:
          requests:
            cpu: 500m
            memory: "2000Mi"
      restartPolicy: Never
